"""
smooth_display.py
=================
Drop-in smooth ECG waveform display module.
Eliminates jitter, teleporting, amplitude jumping, and tearing in all 12 leads.

HOW TO INTEGRATE
----------------
1. Copy this file to your /src/ecg/ directory
2. In your twelve_lead_test.py or expanded_lead_view.py:

    from smooth_display import SmoothECGDisplay

3. Replace your plot setup with:

    self.ecg_display = SmoothECGDisplay(
        plot_widgets=self.plot_widgets,   # dict: {'I': PlotWidget, 'II': PlotWidget, ...}
        sampling_rate=500,
        display_seconds=5,
        adc_center=2048,
        adc_scale=204.8
    )

4. In your serial data callback (data arrival):

    self.ecg_display.push_samples(lead_data_dict)
    # e.g. lead_data_dict = {'I': [2048, 2050, ...], 'II': [...], ...}

5. That's it. The display manages its own render timer internally.

WHAT THIS FIXES
---------------
✅ Jitter from chunked packet arrival
✅ Vertical amplitude jumping (auto-range disabled)
✅ Wrap-around teleport (scrolling cursor eraser)
✅ Per-frame filtfilt() recalculation (incremental lfilter with zi)
✅ PyQtGraph overdraw (clip-to-view, OpenGL, no antialias)
✅ Data/render timer coupling (fully decoupled)
✅ Growing buffers slowing down over time (deque maxlen)
✅ Baseline wander causing vertical drift (rolling baseline subtraction)

REQUIREMENTS
------------
    pip install numpy scipy pyqtgraph PyQt5
    (or PyQt6 — both work)

Author : Generated by Claude (Anthropic) for ECG audit — Feb 2026
"""

import numpy as np
from collections import deque
from scipy.signal import butter, lfilter, lfilter_zi, iirnotch, medfilt
from scipy.ndimage import uniform_filter1d

try:
    from PyQt5.QtCore import QTimer, Qt
    from PyQt5.QtGui import QColor, QPen
    import pyqtgraph as pg
    PYQT_VERSION = 5
except ImportError:
    from PyQt6.QtCore import QTimer, Qt
    from PyQt6.QtGui import QColor, QPen
    import pyqtgraph as pg
    PYQT_VERSION = 6


# ─────────────────────────────────────────────────────────────────────────────
# MODULE-LEVEL PYQTGRAPH CONFIGURATION
# Call configure_pyqtgraph() ONCE at the very top of your main script,
# BEFORE creating any QApplication or widgets.
# ─────────────────────────────────────────────────────────────────────────────

def configure_pyqtgraph():
    """
    Apply global PyQtGraph performance settings.
    MUST be called before creating any PlotWidget instances.
    Call once at the top of your main() or __init__ of your main window.

    Example:
        from smooth_display import configure_pyqtgraph
        configure_pyqtgraph()
        app = QApplication(sys.argv)
        window = MyECGWindow()
    """
    pg.setConfigOptions(
        antialias=False,         # OFF: ~3x faster rendering, imperceptible on ECG lines
        useOpenGL=True,          # GPU-accelerated canvas
        enableExperimental=True, # Required for OpenGL path
        foreground='w',          # White axes/text (dark background)
        background='k',          # Black background — standard ECG monitor look
    )


# ─────────────────────────────────────────────────────────────────────────────
# INCREMENTAL SIGNAL FILTER
# Filters samples AS THEY ARRIVE using lfilter + initial conditions (zi).
# No full-buffer recalculation on every render frame.
# ─────────────────────────────────────────────────────────────────────────────

class IncrementalFilter:
    """
    Applies a digital filter incrementally as new samples arrive.
    Uses scipy.signal.lfilter with maintained state (zi) so each call
    only processes NEW samples — O(n_new) not O(n_buffer).

    This replaces the anti-pattern of calling filtfilt() on the entire
    buffer each render frame.
    """

    def __init__(self, sampling_rate: float = 500.0,
                 lowcut: float = 0.5,
                 highcut: float = 40.0,
                 notch_freq: float = 50.0,
                 notch_q: float = 35.0,
                 order: int = 4,
                 adc_center: float = 2048.0):

        self.fs = sampling_rate
        self.adc_center = adc_center

        # ── Bandpass filter (0.5–40 Hz) ──────────────────────────────────────
        nyq = sampling_rate / 2.0
        low = max(0.001, lowcut / nyq)
        high = min(0.999, highcut / nyq)
        self.b_bp, self.a_bp = butter(order, [low, high], btype='band')

        # ── Notch filter (50 Hz or 60 Hz powerline) ──────────────────────────
        w0 = notch_freq / nyq
        if 0 < w0 < 1:
            self.b_notch, self.a_notch = iirnotch(w0, notch_q)
            self._notch_enabled = True
        else:
            self._notch_enabled = False

        # ── Initial conditions at ADC midpoint (prevents startup spike) ──────
        self.zi_bp = lfilter_zi(self.b_bp, self.a_bp) * adc_center
        if self._notch_enabled:
            self.zi_notch = lfilter_zi(self.b_notch, self.a_notch) * adc_center

    def process(self, samples: np.ndarray) -> np.ndarray:
        """
        Filter new samples and return filtered output.
        Maintains filter state between calls — no startup transients.

        Args:
            samples: 1-D numpy array of new ADC samples

        Returns:
            Filtered samples (same length as input)
        """
        if len(samples) == 0:
            return samples

        samples = np.asarray(samples, dtype=float)

        # Step 1: Notch filter (50/60 Hz removal)
        if self._notch_enabled:
            samples, self.zi_notch = lfilter(
                self.b_notch, self.a_notch, samples, zi=self.zi_notch
            )

        # Step 2: Bandpass (baseline wander + EMG removal)
        filtered, self.zi_bp = lfilter(
            self.b_bp, self.a_bp, samples, zi=self.zi_bp
        )

        return filtered

    def reset(self, value: float = None):
        """Reset filter state. Call when lead is reconnected."""
        v = value if value is not None else self.adc_center
        self.zi_bp = lfilter_zi(self.b_bp, self.a_bp) * v
        if self._notch_enabled:
            self.zi_notch = lfilter_zi(self.b_notch, self.a_notch) * v


# ─────────────────────────────────────────────────────────────────────────────
# SMOOTH LEAD BUFFER
# Fixed-size circular buffer with incremental filtering and baseline tracking.
# ─────────────────────────────────────────────────────────────────────────────

class SmoothLeadBuffer:
    """
    Per-lead data buffer that:
    - Accepts data at any arrival rate
    - Filters incrementally (no per-frame filtfilt)
    - Removes baseline wander with a rolling median baseline
    - Provides stable, fixed-length display arrays
    - Tracks write position for scrolling cursor display
    """

    def __init__(self,
                 sampling_rate: float = 500.0,
                 display_seconds: float = 5.0,
                 adc_center: float = 2048.0,
                 adc_scale: float = 204.8,
                 lead_name: str = '?'):

        self.fs = sampling_rate
        self.adc_center = adc_center
        self.adc_scale = adc_scale  # ADC counts per mV
        self.lead_name = lead_name
        self.display_samples = int(display_seconds * sampling_rate)

        # ── Main circular buffers ─────────────────────────────────────────────
        # Pre-fill with midpoint so display starts flat (not empty/garbage)
        self.raw_buffer = deque(
            [float(adc_center)] * self.display_samples,
            maxlen=self.display_samples
        )
        self.filtered_buffer = deque(
            [0.0] * self.display_samples,
            maxlen=self.display_samples
        )

        # ── Incremental filter ────────────────────────────────────────────────
        self.filt = IncrementalFilter(
            sampling_rate=sampling_rate,
            adc_center=adc_center
        )

        # ── Write position for scrolling cursor ───────────────────────────────
        self.write_pos = 0

        # ── Lead-off detection state ──────────────────────────────────────────
        self.is_lead_off = False
        self._check_window = deque(maxlen=int(sampling_rate * 1.0))  # 1s window

        # ── Baseline tracking (slow rolling median for display centering) ─────
        self._baseline_buffer = deque(maxlen=int(sampling_rate * 2.0))  # 2s
        self._display_baseline = 0.0

    def push(self, samples):
        """
        Push new samples from hardware packet.
        Called in data timer — does filtering and buffering.

        Args:
            samples: list or ndarray of raw ADC values
        """
        if len(samples) == 0:
            return

        arr = np.asarray(samples, dtype=float)

        # Lead-off detection on raw signal
        self._check_window.extend(arr.tolist())
        self.is_lead_off = self._detect_lead_off()

        # Store raw
        self.raw_buffer.extend(arr.tolist())

        if self.is_lead_off:
            # Fill with flat line at center (don't show noise)
            self.filtered_buffer.extend([0.0] * len(arr))
        else:
            # Incremental filter
            filtered = self.filt.process(arr)
            self.filtered_buffer.extend(filtered.tolist())
            self._baseline_buffer.extend(filtered.tolist())
            # Update rolling baseline (very slow — only for vertical centering)
            if len(self._baseline_buffer) > 50:
                self._display_baseline = float(np.median(
                    list(self._baseline_buffer)[-int(self.fs * 0.5):]
                ))

        # Advance write position
        self.write_pos = (self.write_pos + len(arr)) % self.display_samples

    def get_display_array(self) -> np.ndarray:
        """
        Returns correctly-ordered display array (oldest → newest left to right).
        Write position is always at the RIGHT edge.

        Returns:
            np.ndarray shape (display_samples,) in display units (mV centered at 0)
        """
        buf = list(self.filtered_buffer)
        pos = self.write_pos

        # Rotate so write_pos is at right edge
        ordered = buf[pos:] + buf[:pos]
        arr = np.array(ordered, dtype=float)

        # Subtract rolling baseline (removes any residual DC drift)
        arr = arr - self._display_baseline

        return arr

    def get_write_pos_display(self) -> int:
        """
        Returns the current write position in the display array.
        Used to draw the scrolling cursor eraser.
        Always returns self.display_samples - 1 (right edge) since
        get_display_array() rotates so write is always at the right.
        """
        return self.display_samples - 1

    def _detect_lead_off(self) -> bool:
        """Fast lead-off detection on 1-second window."""
        if len(self._check_window) < 50:
            return False
        w = np.array(self._check_window)
        amplitude = float(np.ptp(w))        # Peak-to-peak
        variance = float(np.var(w))

        if amplitude < 20:                   # < ~0.1 mV → flatline
            return True
        if amplitude > 3500:                 # Saturation
            return True
        if variance < 4:                     # True flatline
            return True
        if variance > 300000:                # Pure noise (lead fully off)
            return True
        min_v, max_v = float(np.min(w)), float(np.max(w))
        if min_v <= 5 or max_v >= 4090:     # ADC rail
            return True
        return False

    def reset(self):
        """Reset buffer (call on reconnect or settings change)."""
        self.raw_buffer = deque(
            [float(self.adc_center)] * self.display_samples,
            maxlen=self.display_samples
        )
        self.filtered_buffer = deque(
            [0.0] * self.display_samples,
            maxlen=self.display_samples
        )
        self.filt.reset(self.adc_center)
        self.write_pos = 0
        self._display_baseline = 0.0
        self.is_lead_off = False


# ─────────────────────────────────────────────────────────────────────────────
# SMOOTH LEAD RENDERER
# Wraps a single PyQtGraph PlotWidget for one ECG lead.
# Manages curves, cursor eraser, lead-off overlay, fixed axes.
# ─────────────────────────────────────────────────────────────────────────────

# ECG color scheme — tweak to match your UI
ECG_COLORS = {
    'waveform':    '#00FF41',   # Bright green (classic monitor)
    'cursor':      '#000000',   # Black eraser cursor
    'grid_major':  '#1A3A1A',   # Dark green grid
    'grid_minor':  '#0D1F0D',
    'background':  '#000000',   # Pure black
    'lead_off_bg': '#1A0000',   # Dark red tint when lead disconnected
    'lead_off_txt': '#FF3333',  # Red "LEAD OFF" text
    'label':       '#00AA33',   # Lead name label
}

# Cursor eraser width in samples
CURSOR_ERASE_SAMPLES = 40


class SmoothLeadRenderer:
    """
    Renders one ECG lead smoothly using a PyQtGraph PlotWidget.

    Features:
    - Fixed Y axis (no auto-range jumping)
    - Scrolling cursor eraser (no teleport at wrap-around)
    - Lead-off overlay with red background + "LEAD OFF" text
    - Grid with standard ECG 1mV / 200ms divisions
    - Minimal redraw overhead (clip-to-view, no antialias)
    """

    # Standard ECG display range in filtered units
    DISPLAY_MV_RANGE = 3.0      # ±3 mV display window
    ADC_SCALE = 204.8           # ADC counts per mV (12-bit, ±10V)

    def __init__(self,
                 plot_widget,
                 lead_name: str,
                 display_samples: int = 2500,
                 sampling_rate: float = 500.0):

        self.pw = plot_widget
        self.lead_name = lead_name
        self.display_samples = display_samples
        self.fs = sampling_rate
        self.x_axis = np.arange(display_samples, dtype=float)

        self._lead_off_shown = False

        # ── Configure plot widget ─────────────────────────────────────────────
        self.pw.setBackground(ECG_COLORS['background'])
        self.pw.setMenuEnabled(False)
        self.pw.hideButtons()
        self.pw.setMouseEnabled(x=False, y=False)
        self.pw.setDownsampling(auto=True, mode='peak')
        self.pw.setClipToView(True)

        # Disable all axis labels/ticks for clean look (optional — comment out if you want axes)
        for axis in ['left', 'bottom', 'top', 'right']:
            ax = self.pw.getAxis(axis)
            ax.setStyle(showValues=False, tickLength=0)
            ax.setPen(pg.mkPen(color='#1A3A1A', width=1))

        # ── Fixed axes — SET ONCE, NEVER CHANGE ──────────────────────────────
        # Y axis: filtered signal is centered at 0 (baseline-subtracted)
        # Units are raw ADC-scale counts after bandpass (not mV, not normalized)
        # ±3 mV * 204.8 counts/mV = ±614 counts display range
        y_range = self.DISPLAY_MV_RANGE * self.ADC_SCALE
        self.pw.setYRange(-y_range, y_range, padding=0)
        self.pw.setXRange(0, display_samples, padding=0)

        # CRITICAL: Lock auto-range OFF
        self.pw.enableAutoRange(axis='y', enable=False)
        self.pw.enableAutoRange(axis='x', enable=False)

        # ── ECG grid (1 mV vertical, 200ms horizontal) ────────────────────────
        self._draw_grid()

        # ── Lead name label (top-left) ────────────────────────────────────────
        self.label = pg.TextItem(
            text=lead_name,
            color=ECG_COLORS['label'],
            anchor=(0, 0)
        )
        self.label.setFont(pg.QtGui.QFont('Courier New', 9, pg.QtGui.QFont.Weight.Bold))
        self.pw.addItem(self.label)
        self.label.setPos(10, y_range * 0.85)

        # ── Main waveform curve ───────────────────────────────────────────────
        self.curve = pg.PlotDataItem(
            pen=pg.mkPen(color=ECG_COLORS['waveform'], width=1.5),
            skipFiniteCheck=True,
            dynamicRangeLimit=None,
        )
        self.pw.addItem(self.curve)

        # ── Cursor eraser (black band that sweeps ahead of write head) ────────
        # Creates the classic "sweeping" ECG monitor effect
        self.cursor_curve = pg.PlotDataItem(
            pen=pg.mkPen(color=ECG_COLORS['cursor'], width=CURSOR_ERASE_SAMPLES * 0.8),
            skipFiniteCheck=True,
        )
        self.pw.addItem(self.cursor_curve)

        # ── Lead-off overlay ──────────────────────────────────────────────────
        self.lead_off_text = pg.TextItem(
            text='LEAD OFF',
            color=ECG_COLORS['lead_off_txt'],
            anchor=(0.5, 0.5)
        )
        self.lead_off_text.setFont(
            pg.QtGui.QFont('Courier New', 14, pg.QtGui.QFont.Weight.Bold)
        )
        self.lead_off_text.setPos(display_samples / 2, 0)
        self.lead_off_text.setVisible(False)
        self.pw.addItem(self.lead_off_text)

    def _draw_grid(self):
        """Draw standard ECG grid: major lines every 1mV / 200ms."""
        y_range = self.DISPLAY_MV_RANGE * self.ADC_SCALE

        # Horizontal grid lines (amplitude): every 1 mV
        for mv in np.arange(-self.DISPLAY_MV_RANGE, self.DISPLAY_MV_RANGE + 0.1, 1.0):
            y = mv * self.ADC_SCALE
            line = pg.InfiniteLine(
                pos=y,
                angle=0,
                pen=pg.mkPen(
                    color='#003300' if mv != 0 else '#006600',
                    width=1 if mv != 0 else 2
                )
            )
            self.pw.addItem(line)

        # Vertical grid lines (time): every 200ms = 100 samples at 500 Hz
        samples_per_200ms = int(0.2 * self.fs)
        for s in range(0, self.display_samples, samples_per_200ms):
            line = pg.InfiniteLine(
                pos=s,
                angle=90,
                pen=pg.mkPen(color='#003300', width=1)
            )
            self.pw.addItem(line)

    def render(self, display_array: np.ndarray, is_lead_off: bool):
        """
        Update the waveform display with new data.
        Called by render timer — must be FAST (no computation here).

        Args:
            display_array: Pre-processed array from SmoothLeadBuffer.get_display_array()
            is_lead_off: Whether lead is currently disconnected
        """
        if is_lead_off:
            self._show_lead_off()
            return

        self._hide_lead_off()

        n = len(display_array)
        if n == 0:
            return

        # Main waveform
        self.curve.setData(self.x_axis[:n], display_array)

        # Cursor eraser — draw a black stripe at the right edge (write head)
        # This erases old data just ahead of where new data is being written
        # creating the smooth "sweeping" effect of a real ECG monitor
        erase_start = max(0, n - CURSOR_ERASE_SAMPLES)
        erase_x = self.x_axis[erase_start:n]
        # Fill eraser with zeros (baseline) to "wipe" old waveform
        erase_y = np.zeros(len(erase_x))
        self.cursor_curve.setData(erase_x, erase_y)

    def _show_lead_off(self):
        if not self._lead_off_shown:
            self.pw.setBackground(ECG_COLORS['lead_off_bg'])
            self.lead_off_text.setVisible(True)
            self.curve.setData([], [])          # Clear waveform
            self.cursor_curve.setData([], [])
            self._lead_off_shown = True

    def _hide_lead_off(self):
        if self._lead_off_shown:
            self.pw.setBackground(ECG_COLORS['background'])
            self.lead_off_text.setVisible(False)
            self._lead_off_shown = False

    def set_gain(self, mv_range: float):
        """
        Adjust vertical gain (zoom). Standard ECG gains: 5, 10, 20 mm/mV.
        Call from UI gain selector — does NOT cause jitter because Y range
        is only changed when explicitly requested.

        Args:
            mv_range: Half-range in mV (e.g., 2.0 = ±2mV, 5.0 = ±5mV)
        """
        y = mv_range * self.ADC_SCALE
        self.pw.setYRange(-y, y, padding=0)
        # Update label position
        self.label.setPos(10, y * 0.85)
        # Update DISPLAY_MV_RANGE for grid (optional — redraw grid)
        self.DISPLAY_MV_RANGE = mv_range


# ─────────────────────────────────────────────────────────────────────────────
# SMOOTH ECG DISPLAY — MAIN CLASS
# Drop-in replacement for your existing plot update logic.
# ─────────────────────────────────────────────────────────────────────────────

ALL_LEADS = ['I', 'II', 'III', 'aVR', 'aVL', 'aVF', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6']


class SmoothECGDisplay:
    """
    Complete smooth ECG display manager for all 12 leads.

    Handles:
    - Decoupled data ingestion (any rate) vs render (fixed 20 FPS)
    - Incremental filtering (no full-buffer filtfilt each frame)
    - Fixed Y axes (no auto-range vertical jumping)
    - Scrolling cursor eraser (no wrap-around teleport)
    - Lead-off detection and overlay per lead
    - Thread-safe data push via Qt timer (stays on UI thread)

    USAGE
    -----
        # 1. At app startup (before QApplication):
        configure_pyqtgraph()

        # 2. After creating your plot widgets:
        self.ecg_display = SmoothECGDisplay(
            plot_widgets={'I': self.plot_I, 'II': self.plot_II, ...},
            sampling_rate=500,
            display_seconds=5,
        )

        # 3. In your serial data callback:
        self.ecg_display.push_samples({'I': samples_I, 'II': samples_II, ...})

        # 4. To stop (e.g., on window close):
        self.ecg_display.stop()
    """

    # Render rate: 20 FPS = 50ms. Smooth enough for ECG, not CPU-heavy.
    RENDER_INTERVAL_MS = 50

    def __init__(self,
                 plot_widgets: dict,
                 sampling_rate: float = 500.0,
                 display_seconds: float = 5.0,
                 adc_center: float = 2048.0,
                 adc_scale: float = 204.8,
                 notch_freq: float = 50.0,
                 leads: list = None):
        """
        Args:
            plot_widgets:     Dict mapping lead name → PyQtGraph PlotWidget
                              e.g. {'I': widget_I, 'II': widget_II, ...}
            sampling_rate:    Hardware sampling rate in Hz (default 500)
            display_seconds:  Width of display window in seconds (default 5)
            adc_center:       ADC midpoint value (default 2048 for 12-bit)
            adc_scale:        ADC counts per mV (default 204.8 = ±10mV range)
            notch_freq:       Powerline frequency to notch: 50 (India/EU) or 60 (US)
            leads:            List of lead names to manage. Defaults to all 12.
        """
        self.fs = sampling_rate
        self.display_seconds = display_seconds
        self.display_samples = int(display_seconds * sampling_rate)
        self.adc_center = adc_center
        self.adc_scale = adc_scale
        self.leads = leads or [l for l in ALL_LEADS if l in plot_widgets]

        # ── Per-lead buffers ──────────────────────────────────────────────────
        self.buffers: dict[str, SmoothLeadBuffer] = {}
        for lead in self.leads:
            self.buffers[lead] = SmoothLeadBuffer(
                sampling_rate=sampling_rate,
                display_seconds=display_seconds,
                adc_center=adc_center,
                adc_scale=adc_scale,
                lead_name=lead
            )

        # ── Per-lead renderers ────────────────────────────────────────────────
        self.renderers: dict[str, SmoothLeadRenderer] = {}
        for lead in self.leads:
            if lead in plot_widgets:
                self.renderers[lead] = SmoothLeadRenderer(
                    plot_widget=plot_widgets[lead],
                    lead_name=lead,
                    display_samples=self.display_samples,
                    sampling_rate=sampling_rate
                )

        # ── Render timer (decoupled from data arrival) ────────────────────────
        self._render_timer = QTimer()
        self._render_timer.timeout.connect(self._render_frame)
        self._render_timer.start(self.RENDER_INTERVAL_MS)

        # ── Performance tracking ──────────────────────────────────────────────
        self._frame_count = 0
        self._dropped_frames = 0
        self._last_render_ms = 0

    # ─────────────────────────────────────────────────────────────────────────
    # PUBLIC API
    # ─────────────────────────────────────────────────────────────────────────

    def push_samples(self, lead_data: dict):
        """
        Push new samples from hardware into all lead buffers.
        Call this from your serial/hardware data callback.

        THREAD NOTE: This is safe to call from the UI thread only.
        If your serial reader is on a background thread, use
        push_samples_threadsafe() instead.

        Args:
            lead_data: Dict mapping lead name → list/array of new ADC samples
                       e.g. {'I': [2048, 2052, 2050], 'II': [2100, 2098], ...}
                       Leads not in dict are skipped.
        """
        for lead, samples in lead_data.items():
            if lead in self.buffers and len(samples) > 0:
                self.buffers[lead].push(np.asarray(samples, dtype=float))

    def push_sample_single(self, lead: str, value: float):
        """
        Push a single ADC sample for one lead.
        Convenience method for sample-by-sample ingestion.

        Args:
            lead:  Lead name string e.g. 'II'
            value: Single ADC value (float or int)
        """
        if lead in self.buffers:
            self.buffers[lead].push(np.array([value], dtype=float))

    def push_packet(self, packet: dict):
        """
        Push a single ADC packet (one sample per lead).
        Use when your hardware sends one value per lead per packet.

        Args:
            packet: Dict with one ADC value per lead
                    e.g. {'I': 2048, 'II': 2150, 'III': 2100, ...}
        """
        for lead, value in packet.items():
            if lead in self.buffers:
                self.buffers[lead].push(np.array([float(value)]))

    def set_gain(self, mv_range: float, leads: list = None):
        """
        Set vertical display gain for specified leads (or all leads).

        Args:
            mv_range: Half-range in mV. Standard values:
                      1.0 = ±1mV (2x gain)
                      2.0 = ±2mV (standard)
                      3.0 = ±3mV (default)
                      5.0 = ±5mV (reduced gain)
            leads: List of lead names to apply to. Default: all managed leads.
        """
        target = leads or self.leads
        for lead in target:
            if lead in self.renderers:
                self.renderers[lead].set_gain(mv_range)

    def reset_lead(self, lead: str):
        """
        Reset a single lead buffer and filter state.
        Call when a lead reconnects after being disconnected.

        Args:
            lead: Lead name e.g. 'V1'
        """
        if lead in self.buffers:
            self.buffers[lead].reset()

    def reset_all(self):
        """Reset all lead buffers. Call on restart or new patient."""
        for buf in self.buffers.values():
            buf.reset()

    def get_lead_off_status(self) -> dict:
        """
        Returns lead-off status for all leads.

        Returns:
            Dict mapping lead name → bool (True = disconnected)
            e.g. {'I': False, 'II': False, 'V1': True, ...}
        """
        return {lead: buf.is_lead_off for lead, buf in self.buffers.items()}

    def stop(self):
        """Stop the render timer. Call on window close."""
        self._render_timer.stop()

    def start(self):
        """Restart the render timer after stop()."""
        self._render_timer.start(self.RENDER_INTERVAL_MS)

    def get_performance_stats(self) -> dict:
        """
        Returns rendering performance statistics.
        Useful for debugging jitter / performance issues.

        Returns:
            Dict with frame_count, dropped_frames, last_render_ms
        """
        return {
            'frame_count': self._frame_count,
            'dropped_frames': self._dropped_frames,
            'last_render_ms': self._last_render_ms,
            'render_fps': 1000.0 / max(1, self._last_render_ms)
        }

    # ─────────────────────────────────────────────────────────────────────────
    # INTERNAL RENDER LOOP
    # ─────────────────────────────────────────────────────────────────────────

    def _render_frame(self):
        """
        Called by render timer at fixed 20 FPS.
        Reads from all buffers and calls renderer.render().
        No computation happens here — only buffer reads and setData() calls.
        """
        import time
        t0 = time.perf_counter()

        for lead in self.leads:
            if lead not in self.renderers:
                continue
            buf = self.buffers[lead]
            renderer = self.renderers[lead]

            display_data = buf.get_display_array()
            renderer.render(display_data, buf.is_lead_off)

        self._frame_count += 1
        elapsed_ms = (time.perf_counter() - t0) * 1000
        self._last_render_ms = elapsed_ms

        # Warn if render took longer than the interval (indicates dropped frames)
        if elapsed_ms > self.RENDER_INTERVAL_MS * 0.9:
            self._dropped_frames += 1


# ─────────────────────────────────────────────────────────────────────────────
# THREAD-SAFE VARIANT
# Use this if your serial reader runs in a background QThread.
# ─────────────────────────────────────────────────────────────────────────────

try:
    from PyQt5.QtCore import QObject, pyqtSignal
except ImportError:
    from PyQt6.QtCore import QObject, pyqtSignal


class ThreadSafeSampleQueue(QObject):
    """
    Thread-safe bridge between a background serial thread and the UI thread.
    Use this if your data arrives on a non-UI thread.

    USAGE:
        # Setup (UI thread):
        self.queue = ThreadSafeSampleQueue()
        self.queue.samples_ready.connect(self.ecg_display.push_samples)

        # In background serial thread:
        self.queue.emit_samples({'I': [...], 'II': [...]})
    """
    samples_ready = pyqtSignal(dict)

    def emit_samples(self, lead_data: dict):
        """
        Emit new samples from background thread.
        Qt's signal/slot mechanism marshals this to the UI thread safely.
        """
        self.samples_ready.emit(lead_data)


# ─────────────────────────────────────────────────────────────────────────────
# MINIMAL TEST / DEMO
# Run this file directly to see smooth ECG rendering with synthetic data:
#     python smooth_display.py
# ─────────────────────────────────────────────────────────────────────────────

def _generate_synthetic_ecg_packet(t: float, sampling_rate: float = 500,
                                    heart_rate: float = 75,
                                    noise_level: float = 5.0) -> dict:
    """
    Generate one synthetic ECG packet (10 samples per lead).
    Used only for the demo — replace with your real serial reader.
    """
    samples_per_packet = 10
    dt = 1.0 / sampling_rate
    adc_center = 2048.0

    packet_data = {}
    for lead in ALL_LEADS:
        samples = []
        for i in range(samples_per_packet):
            t_i = t + i * dt
            rr = 60.0 / heart_rate

            # Synthetic PQRST components
            phase = (t_i % rr) / rr
            ecg = 0.0

            # P wave
            p_center = 0.15
            ecg += 200 * np.exp(-((phase - p_center) ** 2) / (2 * 0.015 ** 2))

            # QRS complex
            q_center = 0.30
            ecg -= 100 * np.exp(-((phase - q_center + 0.02) ** 2) / (2 * 0.003 ** 2))
            ecg += 1000 * np.exp(-((phase - q_center) ** 2) / (2 * 0.004 ** 2))
            ecg -= 150 * np.exp(-((phase - q_center - 0.02) ** 2) / (2 * 0.003 ** 2))

            # T wave
            t_center = 0.55
            ecg += 300 * np.exp(-((phase - t_center) ** 2) / (2 * 0.04 ** 2))

            # Lead-specific scaling
            lead_scale = {'II': 1.0, 'I': 0.8, 'III': 0.6, 'aVR': -0.9,
                         'aVL': 0.3, 'aVF': 0.7, 'V1': -0.5, 'V2': 0.4,
                         'V3': 0.7, 'V4': 0.9, 'V5': 0.8, 'V6': 0.6
                         }.get(lead, 0.7)

            ecg *= lead_scale
            ecg += np.random.normal(0, noise_level)
            samples.append(adc_center + ecg)

        packet_data[lead] = samples
    return packet_data


def run_demo():
    """
    Standalone demo: 12-lead ECG with smooth scrolling display.
    Run with: python smooth_display.py
    """
    import sys
    from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget, QGridLayout, QLabel
    from PyQt5.QtCore import QTimer

    # ── Must call BEFORE QApplication ────────────────────────────────────────
    configure_pyqtgraph()

    app = QApplication(sys.argv)

    # ── Main window ───────────────────────────────────────────────────────────
    window = QMainWindow()
    window.setWindowTitle("Smooth ECG Display Demo — smooth_display.py")
    window.resize(1400, 800)
    window.setStyleSheet("background: #000000;")

    central = QWidget()
    window.setCentralWidget(central)
    layout = QGridLayout(central)
    layout.setSpacing(4)
    layout.setContentsMargins(8, 8, 8, 8)

    # ── Create one PlotWidget per lead ────────────────────────────────────────
    LEAD_GRID = [
        ['I',   'aVR', 'V1', 'V4'],
        ['II',  'aVL', 'V2', 'V5'],
        ['III', 'aVF', 'V3', 'V6'],
    ]

    plot_widgets = {}
    for row_idx, row in enumerate(LEAD_GRID):
        for col_idx, lead in enumerate(row):
            pw = pg.PlotWidget()
            layout.addWidget(pw, row_idx, col_idx)
            plot_widgets[lead] = pw

    # ── Create SmoothECGDisplay ───────────────────────────────────────────────
    display = SmoothECGDisplay(
        plot_widgets=plot_widgets,
        sampling_rate=500,
        display_seconds=5,
        adc_center=2048.0,
        adc_scale=204.8,
        notch_freq=50.0
    )

    # ── Synthetic data generator (simulates hardware packets) ─────────────────
    t_current = [0.0]
    dt_packet = 10 / 500.0  # 10 samples at 500 Hz = 20ms per packet

    def generate_and_push():
        packet = _generate_synthetic_ecg_packet(
            t=t_current[0],
            sampling_rate=500,
            heart_rate=75,
            noise_level=5.0
        )
        display.push_samples(packet)
        t_current[0] += dt_packet

    # Data arrives every 20ms (10 samples per packet at 500 Hz)
    data_timer = QTimer()
    data_timer.timeout.connect(generate_and_push)
    data_timer.start(20)

    window.show()

    print("=" * 60)
    print("smooth_display.py DEMO")
    print("=" * 60)
    print(f"Sampling rate : 500 Hz")
    print(f"Display window: 5 seconds")
    print(f"Render rate   : 20 FPS (50ms timer)")
    print(f"Data rate     : 50 FPS (20ms timer, 10 samples/packet)")
    print(f"Leads active  : {len(plot_widgets)}")
    print(f"Buffer size   : {display.display_samples} samples per lead")
    print()
    print("Close the window to exit.")

    sys.exit(app.exec())


if __name__ == '__main__':
    run_demo()
