TRANSLATIONS = {
    "es": {
        "ECG Control Panel": "Panel de control ECG",
        "Save ECG": "Guardar ECG",
        "Open ECG": "Abrir ECG",
        "Working Mode": "Modo de trabajo",
        "Report Setup": "Configuración de informe",
        "Set Filter": "Configurar filtro",
        "System Setup": "Configuración del sistema",
        "Load Default": "Cargar predeterminado",
        "Version": "Versión",
        "Exit": "Salir",
        "Save ECG Details": "Guardar detalles ECG",
        "Open ECG File": "Abrir archivo ECG",
        "Working Mode Settings": "Configuración de modo de trabajo",
        "Filter Settings": "Configuración de filtros",
        "Load Default Settings": "Cargar ajustes predeterminados",
        "Version Information": "Información de versión",
        "Exit Application": "Salir de la aplicación",
        "Wave Speed": "Velocidad de onda",
        "Wave Gain": "Ganancia de onda",
        "Average Wave": "Onda promedio",
        "Lead Sequence": "Secuencia de derivaciones",
        "AC Filter": "Filtro CA",
        "EMG Filter": "Filtro EMG",
        "DFT Filter": "Filtro DFT",
        "BEAT VOL": "VOL LATIDO",
        "LANGUAGE": "Idioma",
        "ECG Settings": "Ajustes ECG",
        "Display Settings": "Ajustes de pantalla",
        "System Settings": "Ajustes del sistema",
        "All Settings": "Todos los ajustes",
        "Calibration": "Calibración",
        "Self Test": "Autoprueba",
        "Memory Reset": "Reinicio de memoria",
        "Factory Reset": "Reinicio de fábrica",
        "Factory Defaults": "Valores predeterminados de fábrica",
        "All settings restored to factory defaults.": "Todos los ajustes se restauraron a los valores de fábrica.",
        "OK": "Aceptar",
        "Cancel": "Cancelar",
        "Apply": "Aplicar",
        "Select": "Seleccionar",
        "Save": "Guardar",
        "No": "No",
        "Yes": "Sí",
        "Adopt Factory Default Config?": "¿Adoptar la configuración predeterminada de fábrica?",
        "The previous configure will be lost!": "¡La configuración anterior se perderá!",
        "Hint": "Consejo",
        "Demo: OFF": "Demostración: OFF",
        "Demo: ON": "Demostración: ON",
        "Capture Screen": "Capturar pantalla",
        "Record Screen": "Grabar pantalla",
        "Stop Recording": "Detener grabación",
        "Recording started": "Grabación iniciada",
        "Start": "Iniciar",
        "Stop": "Detener",
        "Ports": "Puertos",
        "Generate Report": "Generar informe",
        "Back": "Atrás",
        "Return to Dashboard": "Volver al Panel",
        "AI Chatbot": "Chatbot IA",
        "ECG Lead Test 12": "Prueba ECG de 12 derivaciones",
        "Sign Out": "Cerrar sesión",
        "Live Heart Rate Overview": "Resumen de ritmo cardíaco",
        "Stress Level: --": "Nivel de estrés: --",
        "Stress Level:": "Nivel de estrés:",
        "Average Variability: --": "Variabilidad promedio: --",
        "Average Variability:": "Variabilidad promedio:",
        "High": "Alto",
        "Low": "Bajo",
        "Moderate": "Moderado",
        "ECG Recording": "Grabación ECG",
        "Visitors - Last 6 Months ({year})": "Visitantes - Últimos 6 meses ({year})",
        "English": "Inglés",
        "Spanish": "Español",
        "French": "Francés",
        "Close": "Cerrar",
        "Do you want to quit?": "¿Desea salir?",
        "Are you absolutely sure you want to exit?": "¿Está absolutamente seguro de que desea salir?",
        "Software Version": "Versión del Software",
        "Hardware Version": "Versión del Hardware",
        "Firmware Version": "Versión del Firmware",
        "Build Date": "Fecha de Compilación",
        "Manufacturer": "Fabricante",
        "Model": "Modelo",
        "Serial Number": "Número de Serie",
        "License": "Licencia",
        "Saved": "Guardado",
        "Success": "Éxito",
        "Applied": "Aplicado",
        "ECG details saved successfully!": "¡Detalles ECG guardados exitosamente!",
        "ECG file opened successfully!": "¡Archivo ECG abierto exitosamente!",
        "Working mode settings saved and applied to ECG display": "Configuración de modo de trabajo guardada y aplicada a la pantalla ECG",
        "Report settings saved successfully!": "¡Configuración de informe guardada exitosamente!",
        "Filter settings applied successfully!": "¡Configuración de filtros aplicada exitosamente!",
        "System settings saved successfully!": "¡Configuración del sistema guardada exitosamente!",
        "Any unsaved data will be lost!": "¡Cualquier dato no guardado se perderá!",
        "Selected File:": "Archivo seleccionado:",
        "No file selected": "No se seleccionó ningún archivo",
        "Missing Data": "Datos faltantes",
        "Please fill all the fields and select gender.": "Por favor complete todos los campos y seleccione el género.",
        "Error": "Error",
        "Failed to save:": "Error al guardar:",
        "No File": "Sin archivo",
        "Please select a file first!": "¡Por favor seleccione un archivo primero!",
    },
    "fr": {
        "ECG Control Panel": "Panneau de contrôle ECG",
        "Save ECG": "Enregistrer ECG",
        "Open ECG": "Ouvrir ECG",
        "Working Mode": "Mode de travail",
        "Report Setup": "Configuration rapport",
        "Set Filter": "Définir filtre",
        "System Setup": "Configuration système",
        "Load Default": "Charger défaut",
        "Version": "Version",
        "Exit": "Quitter",
        "Save ECG Details": "Enregistrer les détails ECG",
        "Open ECG File": "Ouvrir le fichier ECG",
        "Working Mode Settings": "Paramètres du mode de travail",
        "Filter Settings": "Paramètres des filtres",
        "Load Default Settings": "Charger paramètres par défaut",
        "Version Information": "Informations sur la version",
        "Exit Application": "Quitter l'application",
        "Wave Speed": "Vitesse d'onde",
        "Wave Gain": "Gain d'onde",
        "Average Wave": "Onde moyenne",
        "Lead Sequence": "Séquence des dérivations",
        "AC Filter": "Filtre AC",
        "EMG Filter": "Filtre EMG",
        "DFT Filter": "Filtre DFT",
        "BEAT VOL": "VOL BATTEMENT",
        "LANGUAGE": "Langue",
        "ECG Settings": "Paramètres ECG",
        "Display Settings": "Paramètres d'affichage",
        "System Settings": "Paramètres système",
        "All Settings": "Tous les paramètres",
        "Calibration": "Calibration",
        "Self Test": "Autotest",
        "Memory Reset": "Réinitialisation mémoire",
        "Factory Reset": "Réinitialisation usine",
        "Factory Defaults": "Paramètres d'usine",
        "All settings restored to factory defaults.": "Tous les paramètres ont été restaurés aux valeurs d'usine.",
        "OK": "OK",
        "Cancel": "Annuler",
        "Apply": "Appliquer",
        "Select": "Sélectionner",
        "Save": "Enregistrer",
        "No": "Non",
        "Yes": "Oui",
        "Adopt Factory Default Config?": "Adopter la configuration d'usine ?",
        "The previous configure will be lost!": "La configuration précédente sera perdue !",
        "Hint": "Indice",
        "Demo: OFF": "Démo : OFF",
        "Demo: ON": "Démo : ON",
        "Capture Screen": "Capturer l'écran",
        "Record Screen": "Enregistrer l'écran",
        "Stop Recording": "Arrêter l'enregistrement",
        "Recording started": "Enregistrement commencé",
        "Start": "Démarrer",
        "Stop": "Arrêter",
        "Ports": "Ports",
        "Generate Report": "Générer un rapport",
        "Back": "Retour",
        "Return to Dashboard": "Retour au tableau de bord",
        "AI Chatbot": "Chatbot IA",
        "ECG Lead Test 12": "Test ECG 12 dérivations",
        "Sign Out": "Déconnexion",
        "Live Heart Rate Overview": "Vue du rythme cardiaque",
        "Stress Level: --": "Niveau de stress : --",
        "Stress Level:": "Niveau de stress :",
        "Average Variability: --": "Variabilité moyenne : --",
        "Average Variability:": "Variabilité moyenne :",
        "High": "Élevé",
        "Low": "Faible",
        "Moderate": "Modéré",
        "ECG Recording": "Enregistrement ECG",
        "Visitors - Last 6 Months ({year})": "Visiteurs - 6 derniers mois ({year})",
        "English": "Anglais",
        "Spanish": "Espagnol",
        "French": "Français",
        "Close": "Fermer",
        "Do you want to quit?": "Voulez-vous quitter ?",
        "Are you absolutely sure you want to exit?": "Êtes-vous absolument sûr de vouloir quitter ?",
        "Software Version": "Version du Logiciel",
        "Hardware Version": "Version du Matériel",
        "Firmware Version": "Version du Firmware",
        "Build Date": "Date de Compilation",
        "Manufacturer": "Fabricant",
        "Model": "Modèle",
        "Serial Number": "Numéro de Série",
        "License": "Licence",
        "Saved": "Enregistré",
        "Success": "Succès",
        "Applied": "Appliqué",
        "ECG details saved successfully!": "Détails ECG enregistrés avec succès !",
        "ECG file opened successfully!": "Fichier ECG ouvert avec succès !",
        "Working mode settings saved and applied to ECG display": "Paramètres du mode de travail enregistrés et appliqués à l'affichage ECG",
        "Report settings saved successfully!": "Paramètres de rapport enregistrés avec succès !",
        "Filter settings applied successfully!": "Paramètres de filtre appliqués avec succès !",
        "System settings saved successfully!": "Paramètres système enregistrés avec succès !",
        "Any unsaved data will be lost!": "Toutes les données non enregistrées seront perdues !",
        "Selected File:": "Fichier sélectionné :",
        "No file selected": "Aucun fichier sélectionné",
        "Missing Data": "Données manquantes",
        "Please fill all the fields and select gender.": "Veuillez remplir tous les champs et sélectionner le genre.",
        "Error": "Erreur",
        "Failed to save:": "Échec de l'enregistrement :",
        "No File": "Aucun fichier",
        "Please select a file first!": "Veuillez d'abord sélectionner un fichier !",
    },
    "hi": {
        "ECG Control Panel": "ECG नियंत्रण पैनल",
        "Save ECG": "ECG सहेजें",
        "Open ECG": "ECG खोलें",
        "Working Mode": "कार्य मोड",
        "Report Setup": "रिपोर्ट सेटअप",
        "Set Filter": "फ़िल्टर सेट करें",
        "System Setup": "सिस्टम सेटअप",
        "Load Default": "डिफ़ॉल्ट लोड करें",
        "Version": "संस्करण",
        "Exit": "बाहर निकलें",
        "Save ECG Details": "ECG विवरण सहेजें",
        "Open ECG File": "ECG फ़ाइल खोलें",
        "Working Mode Settings": "कार्य मोड सेटिंग्स",
        "Filter Settings": "फ़िल्टर सेटिंग्स",
        "Load Default Settings": "डिफ़ॉल्ट सेटिंग्स लोड करें",
        "Version Information": "संस्करण जानकारी",
        "Exit Application": "एप्लिकेशन से बाहर निकलें",
        "Wave Speed": "तरंग गति",
        "Wave Gain": "तरंग लाभ",
        "Average Wave": "औसत तरंग",
        "Lead Sequence": "लीड अनुक्रम",
        "AC Filter": "एसी फ़िल्टर",
        "EMG Filter": "ईएमजी फ़िल्टर",
        "DFT Filter": "डीएफटी फ़िल्टर",
        "BEAT VOL": "बीट वॉल्यूम",
        "LANGUAGE": "भाषा",
        "ECG Settings": "ECG सेटिंग्स",
        "Display Settings": "डिस्प्ले सेटिंग्स",
        "System Settings": "सिस्टम सेटिंग्स",
        "All Settings": "सभी सेटिंग्स",
        "Calibration": "अंशांकन",
        "Self Test": "स्व-परीक्षण",
        "Memory Reset": "मेमोरी रीसेट",
        "Factory Reset": "फ़ैक्टरी रीसेट",
        "Factory Defaults": "फ़ैक्टरी डिफ़ॉल्ट",
        "All settings restored to factory defaults.": "सभी सेटिंग्स फ़ैक्टरी डिफ़ॉल्ट पर पुनर्स्थापित कर दी गईं।",
        "OK": "ठीक है",
        "Cancel": "रद्द करें",
        "Apply": "लागू करें",
        "Select": "चुनें",
        "Save": "सहेजें",
        "No": "नहीं",
        "Yes": "हाँ",
        "Adopt Factory Default Config?": "फ़ैक्टरी डिफ़ॉल्ट कॉन्फ़िग अपनाएं?",
        "The previous configure will be lost!": "पिछली कॉन्फ़िग खो जाएगी!",
        "Hint": "संकेत",
        "Demo: OFF": "डेमो: बंद",
        "Demo: ON": "डेमो: चालू",
        "Capture Screen": "स्क्रीन कैप्चर करें",
        "Record Screen": "स्क्रीन रिकॉर्ड करें",
        "Stop Recording": "रिकॉर्डिंग रोकें",
        "Recording started": "रिकॉर्डिंग शुरू की गई",
        "Start": "शुरू करें",
        "Stop": "रोकें",
        "Ports": "पोर्ट",
        "Generate Report": "रिपोर्ट जेनरेट करें",
        "Back": "वापस",
        "Return to Dashboard": "डैशबोर्ड पर वापस जाएँ",
        "AI Chatbot": "AI चैटबॉट",
        "ECG Lead Test 12": "ECG लीड टेस्ट 12",
        "Sign Out": "साइन आउट",
        "Live Heart Rate Overview": "लाइव हृदय गति अवलोकन",
        "Stress Level: --": "तनाव स्तर: --",
        "Stress Level:": "तनाव स्तर:",
        "Average Variability: --": "औसत परिवर्तनशीलता: --",
        "Average Variability:": "औसत परिवर्तनशीलता:",
        "High": "उच्च",
        "Low": "निम्न",
        "Moderate": "मध्यम",
        "ECG Recording": "ECG रिकॉर्डिंग",
        "Visitors - Last 6 Months ({year})": "आगंतुक - पिछले 6 महीने ({year})",
        "English": "अंग्रेज़ी",
        "Spanish": "स्पेनिश",
        "French": "फ़्रेंच",
        "Hindi": "हिंदी",
        "Close": "बंद करें",
        "Do you want to quit?": "क्या आप बाहर निकलना चाहते हैं?",
        "Are you absolutely sure you want to exit?": "क्या आप वाकई बाहर निकलना चाहते हैं?",
        "Software Version": "सॉफ़्टवेयर संस्करण",
        "Hardware Version": "हार्डवेयर संस्करण",
        "Firmware Version": "फ़र्मवेयर संस्करण",
        "Build Date": "बिल्ड तिथि",
        "Manufacturer": "निर्माता",
        "Model": "मॉडल",
        "Serial Number": "सीरियल नंबर",
        "License": "लाइसेंस",
        "Saved": "सहेजा गया",
        "Success": "सफलता",
        "Applied": "लागू किया गया",
        "ECG details saved successfully!": "ECG विवरण सफलतापूर्वक सहेजे गए!",
        "ECG file opened successfully!": "ECG फ़ाइल सफलतापूर्वक खोली गई!",
        "Working mode settings saved and applied to ECG display": "कार्य मोड सेटिंग्स सहेजी गईं और ECG डिस्प्ले पर लागू की गईं",
        "Report settings saved successfully!": "रिपोर्ट सेटिंग्स सफलतापूर्वक सहेजी गईं!",
        "Filter settings applied successfully!": "फ़िल्टर सेटिंग्स सफलतापूर्वक लागू की गईं!",
        "System settings saved successfully!": "सिस्टम सेटिंग्स सफलतापूर्वक सहेजी गईं!",
        "Any unsaved data will be lost!": "कोई भी असहेजित डेटा खो जाएगा!",
        "Selected File:": "चयनित फ़ाइल:",
        "No file selected": "कोई फ़ाइल चयनित नहीं",
        "Missing Data": "डेटा गुम",
        "Please fill all the fields and select gender.": "कृपया सभी फ़ील्ड भरें और लिंग चुनें।",
        "Error": "त्रुटि",
        "Failed to save:": "सहेजने में विफल:",
        "No File": "कोई फ़ाइल नहीं",
        "Please select a file first!": "कृपया पहले एक फ़ाइल चुनें!",
    },
}


def translate_text(text, language="en"):
    if not text:
        return text
    lang = (language or "en").split("-")[0].lower()
    mapping = TRANSLATIONS.get(lang)
    if not mapping:
        return text
    return mapping.get(text, text)

